In [31]:
 import numpy as np

numpy vs list


In [8]:
from time import process_time as pt

In [25]:
start=pt()
py_list=[i for i in range(1000000)]
end=pt()
print(end-start)

0.0625


In [26]:
start=pt()
np_arr=np.array([i for i in range(1000000)])
end=pt()
print(end-start)

0.078125


In [58]:
#convert list to numpy array
l1=["yash","ravi","uday",2]
n=np.asarray(l1)
print(n)

['yash' 'ravi' 'uday' '2']


In [61]:
#analysing a numpy array
ran=np.random.randint(10,20,(5,4))
print(ran.shape)
print(ran.size)

(5, 4)
20


In [63]:
#adding two list
a=[1,32,4,2,2]
b=[3,12,2,1,5]
print(a+b)

[1, 32, 4, 2, 2, 3, 12, 2, 1, 5]


In [62]:
#Adding two np array
a=np.array((1,3,4,3,2))
b=np.array((3,2,52,3,2))
print(a+b)

[ 4  5 56  6  4]


In [27]:
l1=[1,2,3,4]
print(l1)

[1, 2, 3, 4]


In [34]:
arr=np.array([1,2,3,4])
print(np_ar)

[1 2 3 4]


In [35]:
arr.shape

(4,)

In [40]:
#2D array
td_arr=np.array([(1,2,3,4),(2,3,4,5),(3,4,5,6)])
td_arr.shape

(3, 4)

Initial PlaceHolder in numpy array

In [43]:
x =np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
y=np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [47]:
z=np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [55]:
p=np.random.randint(10,20,(3,5))
print(p)

[[12 14 14 18 17]
 [15 19 16 13 14]
 [10 17 19 12 10]]
